name: Build and deploy Node.js project to Azure Function App - pavanireddy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Skipping npm commands as they're not needed
      - name: 'Skip npm Install and Build Steps'
        shell: pwsh
        run: |
          echo "Skipping npm install, build, and test steps as package.json is not needed."
          # Optionally, add any custom commands you need here for your build process
          # ./custom-build-script.sh or other necessary steps

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'pavanireddy'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E4E91064E66242BBAC012EE5B4132236 }}
